### Globals
@baseUrl = http://localhost:3000
@Id-Semsa = "48ad0a1e-3a29-4a80-b162-9782232b83bc"
@Id-Losartana = "a81acba5-6b1b-4be2-80ad-ae8c0fa56c12"
@Acess-Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZDY4OWJiOS0wNzJhLTQzMzMtODE1OS03NzMwZTkwOWU3Y2IiLCJlbWFpbCI6InBlZHJvLnNhbnRvc2Jyb3RpbmhvQGVtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsInVuaWRhZGUiOiI0OGFkMGExZS0zYTI5LTRhODAtYjE2Mi05NzgyMjMyYjgzYmMiLCJpYXQiOjE3Nzc1NDI5MTAsImV4cCI6MTc3NzU0NjUxMCwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.UF5QOOT0PI6eOiLFneiIk5IAfKzFBOUI4CA-0FqOLgQ



### Unidade de Saúde

# @name createUnidade
POST {{baseUrl}}/unidade
Content-Type: application/json
Authorization: Bearer {{Acess-Token}}

{
  "nome": "SEMSA",
  "cnes": "1234567",
  "CEP": 68000000,
  "numero_edificio": 150
}

###
GET {{baseUrl}}/unidade
Authorization: Bearer {{Acess-Token}}


### User

# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer {{Acess-Token}}

{
  "cpf": "32642039285",
  "nome": "Pedro Silva",
  "email": "thepedrosantos@proton.me",
  "password": "Horcruxes7",
  "atribuicao": "Estagiario",
  "comprovante": "2025001039",
  "id_unidade": "48ad0a1e-3a29-4a80-b162-9782232b83bc"
}

###
PATCH {{baseUrl}}/user/dc04d50f-6c53-48f0-9759-e3e483626746
Content-Type: application/json
Authorization: Bearer {{Acess-Token}}

{
  "role": "MANAGER"
}

###
GET {{baseUrl}}/user
Authorization: Bearer {{Acess-Token}}


### Auth

# @name loginAdmin
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "pedro.santosbrotinho@email.com",
  "password": "Horcruxes7"
}

###
# @name loginUser
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "thepedrosantos@proton.me",
  "password": "Horcruxes7"
}

###
# @name loginUser2
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "pedrohenriqiedasilvasantos@gmail.com",
  "password": "Horcruxes7"
}

@authToken = {{loginUser.response.body.accessToken}}


### Medicamento

# @name createRemedy
POST {{baseUrl}}/remedy
Authorization: Bearer {{Acess-Token}}
Content-Type: application/json

{
  "nome": "Losartana 50mg",
  "categoria": "HIPERTENSAO",
  "forma_farmaceutica": "COMPRIMIDO"
}


### Estoque

# @name createStock
POST {{baseUrl}}/stock
Content-Type: application/json
Authorization: Bearer {{Acess-Token}}


{
  "lote": "LOT2026-A",
  "quantidade": 500,
  "data_de_validade": "2034-12-31T00:00:00Z",
  "id_medicamento": {{Id-Losartana}},
  "id_unidade_saude": {{Id-Semsa}}
}


### Pacientes

# @name createPatient
POST {{baseUrl}}/pacientes
Content-Type: application/json

{
  "nome": "Maria Silva",
  "data_nascimento": "1955-08-12T00:00:00Z",
  "cpf": "09876543211",
  "cns": "123456789012345",
  "telefone": "11999999999",
  "endereco": "Rua das Flores, 123 - Bairro Centro",
  "condicao": "Hipertensão",
  "sexo": "F"
}

@pacienteId = {{createPatient.response.body.id}}

###
GET {{baseUrl}}/pacientes/{{pacienteId}}

###
PATCH {{baseUrl}}/pacientes/{{pacienteId}}
Content-Type: application/json

{
  "endereco": "Avenida Nova, 456 - Bairro Sul",
  "telefone": "11888888888"
}

###
DELETE {{baseUrl}}/pacientes/{{pacienteId}}


### Prescrição

# @name createPrescription
POST {{baseUrl}}/prescription
Content-Type: application/json

{
  "data_receita": "2026-04-23T00:00:00Z",
  "uso_continuo": true,
  "via_administracao": "Oral",
  "quantidade_receitada": 30,
  "id_medicamento": {{Id-Losartana}},
  "id_paciente": "ceb71a35-0b49-4d50-9c64-15c9e4daabbe"
}


### Dispensação

# @name createDispensation
POST {{baseUrl}}/dispensation
Content-Type: application/json

{
  "quantidade_solicitada": 30,
  "id_medicamento": {{Id-Losartana}},
  "proxima_retirada": "2026-05-23T00:00:00Z",
  "id_prescricao": "d259baea-e43b-458f-9437-d2a4a7ea407a", 
  "id_usuario": "ad689bb9-072a-4333-8159-7730e909e7cb",
  "id_paciente": "ceb71a35-0b49-4d50-9c64-15c9e4daabbe"
}

###
POST {{baseUrl}}/dispensation/586dc388-f19b-4f77-bddc-c55a301bf1fb/reverse
Content-Type: application/json

{
  "quantidade_devolvida": 30,
  "motivo": "Erro na dosagem ou paciente recusou"
}